version: "3.7"
services:
  app:
    tty: true
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: responder_limit_rate_app
    command: gunicorn -w 4 -k uvicorn.workers.UvicornWorker run:api -b :8000 --log-config logging.conf --threads 4 --timeout 60 --log-level 'debug' --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/local/src/root
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    container_name: responder_limit_rate_redis
    volumes:
      - ./data/redis:/data